heat_template_version: 2015-04-30

description: Deploys a Docker Swarm at MTA CLOUD @ SZTAKI

parameters:
  docker_node_count:
    type: number
    label: Docker Hosts
    description: Number of docker hosts (excluding the master)
    default: 2

  public_ip:
    type: string
    label: Public IP
    description: Public IP address to be assigned to SWARM master
    default: 193.224.59.251

  private_net_name:
    type: string
    label: Private Network Name
    description: Name of private network from which private IP addresses will be allocated
    default: SECSCAN_net

  instance_flavor:
    type: string
    label: Flavor
    default: m1.small
    description: Flavor to use for Docker
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge

  instance_image:
    type: string
    label: Image
    default: Ubuntu 16.04 LTS Cloud image
    description: Image to be used for all servers in this stack

resources:
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
      
  #Networking
  docker_floating_ip:
    type : AWS::EC2::EIPAssociation
    properties :
        InstanceId: { get_resource: docker_master }
        EIP: { get_param: public_ip }
      
  docker_master_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net_name }
      security_groups: [{ get_resource: docker_security_group }]
  
  docker_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description:
      name: docker-security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 2377
          port_range_max: 2377
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535
        - remote_mode: remote_group_id
          protocol: udp
          port_range_min: 1
          port_range_max: 65535

  # Wait condition for swarm token sharing
  master_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: master_wait_handle}
      count: 1
      timeout: 600

  master_wait_handle:
    type: OS::Heat::WaitConditionHandle          
          
  #Master Server
  docker_master:
    type: OS::Nova::Server
    properties:
      name: swarm_master
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_resource: ssh_key }
      networks:
        - port: { get_resource: docker_master_port }
      security_groups:
        - docker-security-group
      user_data_format: RAW
      user_data: 
        str_replace:
          template: |
            #!/bin/bash
            echo "+ startup script starting"
            curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
            sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
            sudo apt-get update
            sudo apt-get -y install docker-engine
            sudo service docker start
            sudo docker swarm init --listen-addr 0.0.0.0:2377
            worker_token=`sudo docker swarm join-token worker -q`
            echo "+ worker token: ${worker_token}"
            echo wc_notify --data-binary "{\"status\": \"SUCCESS\", \"reason\": \"master init done\", \"id\": \"token\", \"data\": \"$worker_token\"}"
            wc_notify --data-binary "{\"status\": \"SUCCESS\", \"reason\": \"master init done\", \"id\": \"token\", \"data\": \"$worker_token\"}"
            echo "+ startup script done"
          params:
            wc_notify: { get_attr: ['master_wait_handle', 'curl_cli'] }
        
  #Other Docker Swarm members
  docker_nodes:
    type: OS::Heat::ResourceGroup
    depends_on: 
        - docker_master
        - master_wait_condition
    properties:
      count: { get_param: docker_node_count }
      resource_def:
        type: OS::Nova::Server
        properties:
            name: swarm_node_%index%
            image: { get_param: instance_image }
            flavor: { get_param: instance_flavor }
            key_name: { get_resource: ssh_key }
            networks:
                - network: { get_param: private_net_name }
            user_data_format: RAW
            user_data:
              str_replace:
                template: |
                  #!/bin/bash
                  echo "+ startup script starting"
                  curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
                  sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
                  sudo apt-get update
                  sudo apt-get -y install docker-engine
                  sudo service docker start
                  echo sudo docker swarm join --token $worker_token $master_ip:2377
                  sudo docker swarm join --token $worker_token $master_ip:2377
                  echo "+ startup script done"
                params:
                  $master_ip: { get_attr: [docker_master, first_address]}
                  $worker_token: { 'Fn::Select': ['token', {get_attr: [master_wait_condition, data]}]}


outputs:
  ssh_private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }
